import * as THREE from "three";
export default [
  {
    id: "10",
    name: "Ovini chair",
    type: "glbModel",
    path: "/models/ovini_chair.glb",
    pathFabric: "/textures/fabric.png",
    pathLegs: "/textures/legs.png",
    annotationFabricPos: new THREE.Vector3(0, 0.55, 0.4),
    annotationFabricMobilePos: new THREE.Vector3(0, 0.7, 0.1),
    annotationLegsPos: new THREE.Vector3(0, 0.15, -0.4),
    annotationLegsMobilePos: new THREE.Vector3(0, -0.1, -0.2),
    cameraPos: new THREE.Vector3(2, 0.35, 0),
    cameraPosMobile: new THREE.Vector3(2.6, 0.35, 0),
    animateFabricDesctop: new THREE.Vector3(0.6, 1.5, 0.4),
    animateFabricMobile: new THREE.Vector3(0.9, 1.5, 0.5),
    animateLegsDesctop: new THREE.Vector3(1, -0.2, 0.3),
    animateLegsMobile: new THREE.Vector3(1.2, -0.8, 0.9),
    animationBodyMobile: new THREE.Vector3(2.4, 0.35, 0),
    animationBodyDesktop: new THREE.Vector3(1.5, 0.35, 0),
    animationFabricMobile: new THREE.Vector3(2, 1.4, 0),
    animationFabricDesktop: new THREE.Vector3(1, 1.4, 0),
    animationLacesMobile: new THREE.Vector3(0.7, 1, -0.9),
    animationLacesDesktop: new THREE.Vector3(0.4, 0.9, 0.5),
    animationLegsMobile: new THREE.Vector3(1.9, -0.3, 0.2),
    animationLegsDesktop: new THREE.Vector3(1.2, -0.3, 0.2),
    fabricIconSizeMobile: { width: 0.2, height: 0.1 },
    fabricIconSizeDesktop: { width: 0.2, height: 0.11 },
    legsIconSizeMobile: { width: 0.21, height: 0.1 },
    legsIconSizeDesktop: { width: 0.2, height: 0.11 },
    parts: [
      { id: "body", label: "Body" },
      { id: "fabric", label: "Fabric" },
      { id: "laces", label: "Laces" },
      { id: "legs", label: "Legs" },
    ],
    colors: [
      { name: "LIGHT-WOOD", color: "#d4c8a3" },
      { name: "BLACK", color: "#444444" },
      { name: "RED", color: "#FF0000" },
      { name: "BLUE", color: "#0000FF" },
      { name: "GREEN", color: "#6AA84F" },
      { name: "ORANGE", color: "#E69138" },
    ],
    materials: {
      body: "metal_mat",
      fabric: "fabric_mat",
      laces: "laces_mat",
      legs: "wood_mat",
    },
  },
  {
    id: "11",
    name: "Tamarack chair",
    type: "glbModel",
    path: "/models/tamarack_chair.glb",
    pathFabric: "/textures/front.png",
    pathLegs: "/textures/back.png",
    annotationFabricPos: new THREE.Vector3(0, 0.65, 0.4),
    annotationFabricMobilePos: new THREE.Vector3(0, 0.9, 0.3),
    annotationLegsPos: new THREE.Vector3(0, 0.15, -0.6),
    annotationLegsMobilePos: new THREE.Vector3(0.1, -0.55, -0.3),
    cameraPos: new THREE.Vector3(1.7, 1.3, 1.5),
    cameraPosMobile: new THREE.Vector3(1.9, 1.5, 1.9),
    animateFabricDesctop: new THREE.Vector3(1, 1.5, 0.4),
    animateFabricMobile: new THREE.Vector3(1, 1, 1.5),
    animateLegsDesctop: new THREE.Vector3(1, -0.2, -1.3),
    animateLegsMobile: new THREE.Vector3(1.5, 1, -2),
    animationBodyMobile: new THREE.Vector3(3, 1.5, 0.9),
    animationBodyDesktop: new THREE.Vector3(1.8, 1, 0.5),
  
    fabricIconSizeMobile: { width: 0.2, height: 0.1 },
    fabricIconSizeDesktop: { width: 0.18, height: 0.09 },
    legsIconSizeMobile: { width: 0.26, height: 0.15 },
    legsIconSizeDesktop: { width: 0.22, height: 0.12 },
    parts: [{ id: "body", label: "Body" }],
    colors: [
      { name: "LIGHT-WOOD", color: "#d4c8a3" },
      { name: "BLACK", color: "#444444" },
      { name: "RED", color: "#FF0000" },
      { name: "BLUE", color: "#0000FF" },
      { name: "GREEN", color: "#6AA84F" },
      { name: "ORANGE", color: "#E69138" },
    ],

    materials: {
      body: "tamarack_mat",
    },
  },
  {
    id: "12",
    name: "menu_tailor_sofa",
    type: "glbModel",
    path: "/models/menu_tailor_sofa.glb",
    pathFabric: "/textures/fabric.png",
    pathLegs: "/textures/legs.png",
    annotationFabricPos: new THREE.Vector3(-0.4, 0.80, 0.4),
    annotationFabricMobilePos: new THREE.Vector3(-0.2, 0.9, 0.1),
    annotationLegsPos: new THREE.Vector3(0.3, -0.2, -0.4),
    annotationLegsMobilePos: new THREE.Vector3(0.2, -0.2, -0.2),
    cameraPos: new THREE.Vector3(2, 0.9, 2),
    cameraPosMobile: new THREE.Vector3(3.3, 0.9, 5),
    animateFabricDesctop: new THREE.Vector3(2, 1.5, 0.8),
    animateFabricMobile:  new THREE.Vector3(2.3, 0.9, 5),
    animateLegsDesctop: new THREE.Vector3(2, 0.2, -0.3),
    animateLegsMobile: new THREE.Vector3(3.3, 0.9, -5),
    animationBodyMobile: new THREE.Vector3(4, 0.9, 5),
    animationBodyDesktop: new THREE.Vector3(2.2, 0.7, 2.2),
    animationFabricMobile: new THREE.Vector3(3.7, 2, -2.9),
    animationFabricDesktop: new THREE.Vector3(1.2, 1.3, -2),
    fabricIconSizeMobile: { width: 0.25, height: 0.15 },
    fabricIconSizeDesktop: { width: 0.2, height: 0.11 },
    legsIconSizeMobile: { width: 0.28, height: 0.15 },
    legsIconSizeDesktop: { width: 0.2, height: 0.11 },
    parts: [
      { id: "body", label: "Body" },
      { id: "fabric", label: "Frame" },
    ],
    colors: [
      { name: "LIGHT-WOOD", color: "#d4c8a3" },
      { name: "BLACK", color: "#444444" },
      { name: "RED", color: "#FF0000" },
      { name: "BLUE", color: "#0000FF" },
      { name: "GREEN", color: "#6AA84F" },
      { name: "ORANGE", color: "#E69138" },
    ],
    materials: {
      body: "mt_fabric_mat",
      fabric: "mt_wood_mat",
    },
  },
];
